[package]
name = "json-rs"
version = "0.0.1"
edition = "2018"

[dependencies]
memmap = "0.7.0"
serde = "1.0.103"
serde_derive = "1.0.103"
serde_json = "1.0.44"
jq-rs = "0.4.1"

[profile.release]
lto = true

[[bin]]
name = "json-value-rs"
path = "src/json_value.rs"

[[bin]]
name = "json-struct-rs"
path = "src/json_struct.rs"

[[bin]]
name = "json-pull-rs"
path = "src/json_pull.rs"

[[bin]]
name = "json-jq-rs"
path = "src/json_jq.rs"
